Feat/home 64 new node red schedules
inzynierka-home-iot/frontend-rncli pull request #41
Opened 2023-12-16 21:48 UTC by mgumis15

2023-12-16 22:13 UTC, mateusz-kleszcz reviewed
The code looks well, but I can't run it, probably because of the `yarn.lock` changes. Try to run `yarn install` before the push

2023-12-16 22:13 UTC, mateusz-kleszcz commented on views/BuzzerView/components/TurnOnBuzzerSelect/TurnOnBuzzerSelect.tsx
> +        label="Włączaj automatycznie brzęczyk, jezeli czujnik wykryje ruch"
```suggestion
        label="Włączaj automatycznie alarm, jeżeli czujnik wykryje ruch"
```
alarm or brzęczyk? 🤔

2023-12-16 22:13 UTC, mateusz-kleszcz commented on views/SprinklerView/SprinklerView.tsx
> +  };
It's safer to pass `action` parameters separately in each API request. Also, you don't have to destructure values and move them to the new object.

2023-12-16 22:13 UTC, mateusz-kleszcz commented on views/SprinklerView/TurnOnFanSelect/TurnOnSprinklerSelect.tsx
> +  sprinklerBaseParams: any;
Set proper type to fanBaseParams like TempSensorBaseParams in [TempSensorView.tsx](https://github.com/inzynierka-home-iot/frontend-rncli/pull/21/files#diff-df6eb1cf97e6dff09228f26e4c6502f320c9454dd41bd61477c99a5f9e95cac8)

2023-12-17 18:00 UTC, Phabes commented on views/SprinklerView/TurnOnFanSelect/TurnOnSprinklerSelect.tsx
> +        label="Włączaj automatycznie zraszacz, jezeli czujniki światła i wilgotności uzyskają ustawione wartości."
```suggestion
        label="Włączaj automatycznie zraszacz, jeżeli czujniki światła i wilgotności uzyskają ustawione wartości."
```

2023-12-17 18:07 UTC, Phabes requested changes
Add sprinkler to mock devices and modify existing buzzer (simply add  `schedule: {}` to it). While merging to main `useSelectValue` should raise conflict because current name is `useSelectIndex`)

2024-01-03 23:55 UTC, mateusz-kleszcz approved these changes

2024-01-04 00:20 UTC, Phabes approved these changes

2024-01-04 00:20 UTC, merged